=== software-provider/coindatabase/coindatabase-master/coin_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z ]+[A-Za-z]$"
        },
        "symbol": {
            "type": "string",
            "pattern": "^[A-Z]{3,10}$"
        },
        "website_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "blockchain_explorer_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "announcement_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "nodes_explorer_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "message_board_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "twitter_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "reddit_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "wikipedia_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "repo_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "whitepaper_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "telegram_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "max_supply": {
            "$ref": "#/definitions/extended_number"
        },
        "genesis_block_date": {
            "type": "string"
        },
        "consensus": {
            "oneOf": [
                {"$ref": "#/definitions/consensus_type"},
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/defintions/consensus_type"
                    }
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "blockchain_model": {
            "oneOf": [
                {"$ref": "#/definitions/blockchain_model_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "hash_algo": {
            "type": "string"
        },
        "block_time": {
            "$ref": "#/definitions/extended_number"
        },
        "tx_min_fee": {
            "$ref": "#/definitions/extended_number"
        },
        "block_max_size": {
            "$ref": "#/definitions/data_size"
        },
        "block_reward": {
            "$ref": "#/definitions/extended_number"
        },
        "tx_per_second": {
            "$ref": "#/definitions/extended_number"
        },
        "core_lang": {
            "type": "string"
        },
        "smart_contracts": {
            "oneOf": [
                {"$ref": "#/definitions/smart_contracts_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "tx_anonymity": {
            "oneOf": [
                {"$ref": "#/definitions/tx_anonymity_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "masternode": {
            "$ref": "#/definitions/extended_boolean"
        },
        "masternode_deposit": {
            "$ref": "#/definitions/extended_number"
        },
        "treasury": {
            "$ref": "#/definitions/extended_boolean"
        },
        "governance": {
            "$ref": "#/definitions/extended_boolean"
        },
        "wikipedia_description": {
            "$ref": "#/definitions/extended_string"
        },
        "references": {
            "type": "object",
            "properties": {
                "name": {"$ref": "#/definitions/list-of-urls"},
                "symbol": {"$ref": "#/definitions/list-of-urls"},
                "website_url": {"$ref": "#/definitions/list-of-urls"},
                "blockchain_explorer_url": {"$ref": "#/definitions/list-of-urls"},
                "announcement_url": {"$ref": "#/definitions/list-of-urls"},
                "nodes_explorer_url": {"$ref": "#/definitions/list-of-urls"},
                "message_board_url": {"$ref": "#/definitions/list-of-urls"},
                "twitter_url": {"$ref": "#/definitions/list-of-urls"},
                "reddit_url": {"$ref": "#/definitions/list-of-urls"},
                "wikipedia_url": {"$ref": "#/definitions/list-of-urls"},
                "repo_url": {"$ref": "#/definitions/list-of-urls"},
                "whitepaper_url": {"$ref": "#/definitions/list-of-urls"},
                "telegram_url": {"$ref": "#/definitions/list-of-urls"},
                "max_supply": {"$ref": "#/definitions/list-of-urls"},
                "genesis_block_date": {"$ref": "#/definitions/list-of-urls"},
                "consensus": {"$ref": "#/definitions/list-of-urls"},
                "hash_algo": {"$ref": "#/definitions/list-of-urls"},
                "block_time": {"$ref": "#/definitions/list-of-urls"},
                "block_max_size": {"$ref": "#/definitions/list-of-urls"},
                "block_reward": {"$ref": "#/definitions/list-of-urls"},
                "tx_per_second": {"$ref": "#/definitions/list-of-urls"},
                "core_lang": {"$ref": "#/definitions/list-of-urls"},
                "smart_contracts": {"$ref": "#/definitions/list-of-urls"},
                "tx_anonymity": {"$ref": "#/definitions/list-of-urls"},
                "tx_min_fee": {"$ref": "#/definitions/list-of-urls"},
                "blockchain_model": {"$ref": "#/definitions/list-of-urls"},
                "masternode": {"$ref": "#/definitions/list-of-urls"},
                "masternode_deposit": {"$ref": "#/definitions/list-of-urls"},
                "treasury": {"$ref": "#/definitions/list-of-urls"},
                "governance": {"$ref": "#/definitions/list-of-urls"},
                "wikipedia_description": {"$ref": "#/definitions/list-of-urls"}
            },
            "additionalProperties": false
        }
    },
    "definitions": {
        "extended_number": {
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "string",
                    "pattern": "^\\d(?:[.\\d]*\\d)?(K|M|B)"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?", "Inf"]
                }
            ]
        },
        "extended_boolean": {
            "oneOf": [
                {
                    "type": "boolean"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "extended_string": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "data_size": {
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "string",
                    "pattern": "^\\d+(KB|MB|GB)"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?", "Inf"]
                }
            ]
        },
        "smart_contracts_type": {
            "type": "string",
            "enum": ["none", "limited", "rich"]
        },
        "tx_anonymity_type": {
            "type": "string",
            "enum": ["never", "optional", "always"]
        },
        "consensus_type": {
            "type": "string",
            "enum": ["proof-of-work", "proof-of-stake", "proof-of-importance"]
        },
        "blockchain_model_type": {
            "type": "string",
            "enum": ["UTXO", "account"]
        },
        "list-of-urls": {
            "type": "array",
            "minItems": 0,
            "maxItems": 3,
            "items": {
                "type": "string",
                "pattern": "^https?://.+"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "symbol",
        "website_url",
        "blockchain_explorer_url",
        "announcement_url",
        "nodes_explorer_url",
        "message_board_url",
        "twitter_url",
        "reddit_url",
        "wikipedia_url",
        "repo_url",
        "whitepaper_url",
        "telegram_url",
        "max_supply",
        "genesis_block_date",
        "consensus",
        "hash_algo",
        "block_time",
        "block_max_size",
        "block_reward",
        "tx_per_second",
        "tx_min_fee",
        "tx_anonymity",
        "core_lang",
        "smart_contracts",
        "blockchain_model",
        "references",
        "masternode",
        "masternode_deposit",
        "treasury",
        "governance",
        "wikipedia_description"
    ]
}

=== software-provider/coindatabase/coindatabase-master/coin/Dash.json
{
    "name": "Dash",
    "symbol": "DASH",
    "website_url": [
        "https://www.dash.org",
        "http://dashorg64cjvj4s3.onion",
        "https://dashpay.atlassian.net/wiki"
    ],
    "blockchain_explorer_url": [
        "https://explorer.dash.org/chain/Dash",
        "https://chainz.cryptoid.info/dash/",
        "https://bitinfocharts.com/dash/explorer/"
    ],
    "nodes_explorer_url": [
        "https://chainz.cryptoid.info/dash/masternodes.dws",
        "https://bitinfocharts.com/dash/nodes-active/",
        "https://www.dashninja.pl/masternodes.html"
    ],
    "message_board_url": [
        "https://www.dash.org/forum/"
    ],
    "twitter_url": [
        "https://twitter.com/Dashpay"
    ],
    "reddit_url": [
        "http://www.reddit.com/r/dashpay/"
    ],
    "telegram_url": [
        "https://t.me/DashDigitalCash"
    ],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/Dash_(cryptocurrency)"
    ],
    "repo_url": [
        "https://github.com/dashpay/dash"
    ],
    "whitepaper_url": [
        "https://www.dash.org/wp-content/uploads/2015/04/Dash-WhitepaperV1.pdf",
        "https://github.com/dashpay/dash/wiki/Whitepaper",
        "https://www.dash.org/binaries/evo/DashPaper-v13-v1.pdf"
    ],
    "announcement_url": [
        "https://bitcointalk.org/index.php?topic=421615.0"
    ],
    "max_supply": "18.6M",
    "genesis_block_date": "2014-01-19",
    "consensus": "proof-of-work",
    "hash_algo": "X11",
    "block_time": 150,
    "block_max_size": "1MB",
    "block_reward": 3.6,
    "tx_per_second": 28,
    "tx_min_fee": 0,
    "tx_anonymity": "optional",
    "core_lang": "C++",
    "smart_contracts": "limited",
    "blockchain_model": "UTXO",
    "masternode": true,
    "masternode_deposit": 1000,
    "treasury": true,
    "governance": true,
    "wikipedia_description": "Dash (formerly known as Darkcoin and XCoin) is an open source peer-to-peer cryptocurrency that offers all the same features as Bitcoin but also has advanced capabilities, including instant transactions (InstantSend), private transactions (PrivateSend), and decentralized governance (DGBB). Dash's decentralized governance and budgeting system makes it the first decentralized autonomous organization. Dash uses a two-tier architecture to power its network. The first tier consists of miners who secure the network and write transactions to the blockchain. The second tier consists of masternodes which enable the advanced features of Dash.",
    "references": {
        "genesis_block_date": [
            "https://chainz.cryptoid.info/dash/block.dws?1.htm"
        ],
        "hash_algo": [
            "https://www.dash.org/wp-content/uploads/2015/04/Dash-WhitepaperV1.pdf"
        ],
        "consensus": [
            "https://www.reddit.com/r/dashpay/comments/5zdmom/why_is_dash_not_considered_pos/"
        ],
        "max_supply": [
            "https://dash.org.ru/pages/emission.php",
            "https://www.dashtreasury.org/faq-general.html"
        ],
        "block_time": [
            "https://www.reddit.com/r/dashpay/comments/3yt70h/so_i_have_to_ask_the_question_what_is_dashs/"
        ],
        "block_max_size": [
            "https://www.reddit.com/r/dashpay/comments/3yt70h/so_i_have_to_ask_the_question_what_is_dashs/"
        ],
        "block_reward": [
            "https://bitinfocharts.com/dash/explorer/"
        ],
        "tx_per_second": [
            "https://www.reddit.com/r/dashpay/comments/5yw0yy/how_many_transactions_per_second_can_dash_handle/"
        ],
        "tx_min_fee": [
            "https://www.reddit.com/r/dashpay/comments/5yw0yy/how_many_transactions_per_second_can_dash_handle/"
        ],
        "core_lang": [
            "https://github.com/dashpay/dash"
        ],
        "smart_contracts": [
            "https://github.com/dashpay/bitcore-lib-dash/blob/master/docs/script.md"
        ],
        "blockchain_model": [
            "https://github.com/dashpay/dash/wiki/Whitepaper"
        ],
        "masternode": [
            "https://github.com/dashpay/dash/wiki/Whitepaper"
        ],
        "masternode_deposit": [
            "https://github.com/dashpay/dash/wiki/Whitepaper"
        ],
        "tx_anonymity": [
            "https://www.dash.org/darksend/"
        ],
        "governance": [
            "https://www.dash.org/forum/threads/self-sustainable-decentralized-governance-by-blockchain.4708/",
            "https://dashvotetracker.com/"
        ],
        "treasury": [
            "https://www.dashtreasury.org/"
        ],
        "wikipedia_description": [
            "https://en.wikipedia.org/wiki/Dash_(cryptocurrency)"
        ]
    }
}

=== software-provider/coindatabase/coindatabase-master/coin/Ethereum_Classic.json
{
    "name": "Ethereum Classic",
    "symbol": "ETC",
    "website_url": [
        "https://ethereumclassic.github.io"
    ],
    "blockchain_explorer_url": [
        "https://gastracker.io/",
        "https://etcchain.com/explorer",
        "http://etherhub.io/home"
    ],
    "nodes_explorer_url": [],
    "message_board_url": [],
    "twitter_url": [
        "https://twitter.com/eth_classic"
    ],
    "reddit_url": [
        "https://www.reddit.com/r/EthereumClassic/"
    ],
    "telegram_url": [
        "https://telegram.me/ethclassic"
    ],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/Ethereum_Classic"
    ],
    "repo_url": [
        "https://github.com/ethereumproject/go-ethereum"
    ],
    "whitepaper_url": [
        "https://github.com/ethereum/wiki/wiki/White-Paper"
    ],
    "announcement_url": [
        "https://bitcointalk.org/index.php?topic=1559630.0"
    ],
    "max_supply": "Inf",
    "genesis_block_date": "2015-07-30",
    "consensus": "proof-of-work",
    "hash_algo": "Ethash",
    "block_time": 15,
    "block_max_size": "Inf",
    "block_reward": 5,
    "tx_per_second": 15,
    "tx_min_fee": "?",
    "tx_anonymity": "never",
    "core_lang": "go",
    "smart_contracts": "rich",
    "blockchain_model": "account",
    "masternode": false,
    "masternode_deposit": "NA",
    "treasury": false,
    "governance": false,
    "wikipedia_description": "Ethereum Classic is an open-source, public, blockchain-based distributed computing platform featuring smart contract (scripting) functionality. It provides a decentralized Turing-complete virtual machine, the Ethereum Virtual Machine (EVM), which can execute scripts using an international network of public nodes. Ethereum Classic also provides a value token called \"classic ether\", which can be transferred between participants and is used to compensate participant nodes for computations performed. The classic ether token is traded on cryptocurrency exchanges under the code ETC. Gas, an internal transaction pricing mechanism, is used to prevent spam on the network and allocate resources proportionally to the incentive offered by the request.",
    "references": {
        "blockchain_model": [
            "https://medium.com/@ConsenSys/thoughts-on-utxo-by-vitalik-buterin-2bb782c67e53",
            "https://github.com/ethereum/wiki/wiki/Design-Rationale"
        ],
        "max_supply": [
            "https://www.etcdevteam.com/blog/articles/a-joint-statement-ecip1017.html"
        ],
        "genesis_block_date": [
            "https://gastracker.io/block/1"
        ],
        "consensus": [
            "https://steemit.com/eth/@daut44/musings-on-ethereum-ethereum-classic",
            "http://ethereum-classic-guide.readthedocs.io/en/latest/mining.html"
        ],
        "hash_algo": [
            "http://ethereum-classic-guide.readthedocs.io/en/latest/mining.html",
            "https://github.com/ethereum/wiki/wiki/Ethash"
        ],
        "block_time": [
            "http://ethereum-classic-guide.readthedocs.io/en/latest/mining.html"
        ],
        "block_max_size": [
            "https://ethereum.stackexchange.com/questions/1106/is-there-a-limit-for-transaction-size/1110#1110"
        ],
        "block_reward": [
            "https://www.cryptocompare.com/coins/etc/overview/BTC"
        ],
        "tx_per_second": [
            "https://medium.com/@yobanjo/ethereum-wont-scale-like-you-ve-been-told-cae445bef539"
        ],
        "core_lang": [
            "https://github.com/ethereumproject/go-ethereum"
        ],
        "smart_contracts": [
            "https://github.com/ethereumclassic/faq#user-content-what-is-a-smart-contract"
        ],
        "masternode": [
            "https://ethereum-classic-guide.readthedocs.io/en/latest/network/connecting-to-the-network.html#the-ethereum-network"
        ],
        "masternode_deposit": [
            "https://ethereum-classic-guide.readthedocs.io/en/latest/network/connecting-to-the-network.html#the-ethereum-network"
        ],
        "tx_anonymity": [
            "https://www.reddit.com/r/ethereum/comments/3uwo9y/anonymity_in_ethereum/"
        ],
        "treasury": [
            "https://github.com/ethereum/wiki/wiki/White-Paper"
        ],
        "governance": [
            "https://github.com/ethereum/wiki/wiki/White-Paper"
        ],
        "wikipedia_description": [
            "https://en.wikipedia.org/wiki/Ethereum_Classic"
        ]
    }
}

=== software-provider/coindatabase/coindatabase-master/coin/NEM.json
{
    "name": "NEM",
    "symbol": "XEM",
    "website_url": [
        "https://www.nem.io/",
        "http://wiki.nem.io/index.php/Main_Page"
    ],
    "blockchain_explorer_url": [
        "http://chain.nem.ninja/#/blocks/0"
    ],
    "nodes_explorer_url": [
        "http://chain.nem.ninja/#/nodes/",
        "https://www.nodeexplorer.com/index"
    ],
    "message_board_url": [
        "https://forum.nem.io/"
    ],
    "twitter_url": [
        "https://twitter.com/NEMofficial"
    ],
    "reddit_url": [
        "https://www.reddit.com/r/nem/"
    ],
    "telegram_url": [
        "https://t.me/nemred"
    ],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/NEM_(cryptocurrency)"
    ],
    "repo_url": [
        "https://github.com/NemProject/nem.core"
    ],
    "whitepaper_url": [
        "https://www.nem.io/NEM_techRef.pdf"
    ],
    "announcement_url": [
        "https://bitcointalk.org/index.php?topic=654845.0"
    ],
    "max_supply":  8999999999,
    "genesis_block_date": "2015-03-29",
    "consensus": "proof-of-importance",
    "hash_algo": "SHA3-256",
    "block_time": 60,
    "block_max_size": "?",
    "block_reward": 0,
    "tx_per_second": 2,
    "tx_min_fee": "?",
    "tx_anonymity": "never",
    "core_lang": "Java",
    "smart_contracts": "limited",
    "blockchain_model": "account",
    "masternode": true,
    "masternode_deposit": "3M",
    "treasury": true,
    "governance": false,
    "wikipedia_description": "NEM is a peer-to-peer cryptocurrency and blockchain platform launched on March 31, 2015. Written in Java, with a C++ version in the works, NEM has a stated goal of a wide distribution model and has introduced new features to blockchain technology such as its proof-of-importance (POI) algorithm, multisignature accounts, encrypted messaging, and an Eigentrust++ reputation system. The NEM blockchain software is used in a commercial blockchain called Mijin, which is being tested by financial institutions and private companies in Japan and internationally.",
    "references": {
        "hash_algo": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "blockchain_model": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "max_supply": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "genesis_block_date": [
            "http://chain.nem.ninja/#/block/1"
        ],
        "block_time": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "tx_per_second": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "treasury": [
            "https://forum.nem.io/t/nem-supernode-rewards-program/1735",
            "https://blog.nem.io/update-sustainability-fund-final-redemption-numbers/"
        ],
        "masternode": [
            "https://forum.nem.io/t/nem-supernode-rewards-program/1735"
        ],
        "masternode_deposit": [
            "https://forum.nem.io/t/nem-supernode-rewards-program/1735"
        ],
        "smart_contracts": [
            "https://blog.nem.io/ethereum-versus-nem-the-obvious-choice/"
        ],
        "tx_anonymity": [
            "https://forum.nem.io/t/anonymous-transactions/649"
        ],
        "governance": [
            "https://forum.nem.io/t/financing-nem-development-dash-style/3604/13"
        ],
        "consensus": [
            "https://blog.nem.io/the-beginners-guide-to-nem/",
            "https://blog.nem.io/what-are-poi-and-vesting/"
        ],
        "block_reward": [
            "https://forum.nem.io/t/harvesting-blocks/4031/3"
        ],
        "core_lang": [
            "https://github.com/NemProject/nem.core"
        ],
        "blockchain_model": [
            "https://www.nem.io/NEM_techRef.pdf"
        ],
        "wikipedia_description": [
            "https://en.wikipedia.org/wiki/NEM_(cryptocurrency)"
        ]

    }
}

=== software-provider/coindatabase/coindatabase-master/coin/Bitcoin.json
{
    "name": "Bitcoin",
    "symbol": "BTC",
    "website_url": [
        "https://bitcoin.org",
        "https://www.bitcoin.com"
    ],
    "blockchain_explorer_url": [
        "https://blockchain.info",
        "https://chainquery.com/bitcoin-api",
        "https://www.walletexplorer.com"
    ],
    "nodes_explorer_url": [
        "https://coin.dance/nodes",
        "https://bitnodes.21.co"
    ],
    "message_board_url": [
        "https://bitcointalk.org",
        "https://forum.bitcoin.com"
    ],
    "twitter_url": [
        "https://twitter.com/Bitcoin"
    ],
    "reddit_url": [
        "https://www.reddit.com/r/Bitcoin"
    ],
    "telegram_url": [
        "https://t.me/BitcoinCore"
    ],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/Bitcoin"
    ],
    "repo_url": [
        "https://github.com/bitcoin/bitcoin"
    ],
    "whitepaper_url": [
        "https://bitcoin.org/bitcoin.pdf"
    ],
    "announcement_url": [],
    "max_supply": "21M",
    "genesis_block_date": "2009-01-03",
    "consensus": "proof-of-work",
    "hash_algo": "SHA-256",
    "block_time": 600,
    "block_max_size": "1MB",
    "block_reward": 12.5,
    "tx_per_second": 7,
    "tx_min_fee": "?",
    "tx_anonymity": "never",
    "core_lang": "C++",
    "smart_contracts": "limited",
    "blockchain_model": "UTXO",
    "masternode": false,
    "masternode_deposit": "NA",
    "treasury": false,
    "governance": false,
    "wikipedia_description": "Bitcoin is a cryptocurrency and a digital payment system invented by an unknown programmer, or a group of programmers, under the name Satoshi Nakamoto. It was released as open-source software in 2009. The system is peer-to-peer, and transactions take place between users directly, without an intermediary. These transactions are verified by network nodes and recorded in a public distributed ledger called a blockchain. Since the system works without a central repository or single administrator, bitcoin is called the first decentralized digital currency. Besides being created as a reward for mining, bitcoin can be exchanged for other currencies, products, and services in legal or black markets. As of February 2015, over 100,000 merchants and vendors accepted bitcoin as payment. According to research produced by Cambridge University in 2017, there are 2.9 to 5.8 million unique users using a cryptocurrency wallet, most of them using bitcoin.",
    "references": {
        "blockchain_model": [
            "https://bitcoin.stackexchange.com/a/20623",
            "https://medium.com/@ConsenSys/thoughts-on-utxo-by-vitalik-buterin-2bb782c67e53",
            "https://github.com/ethereum/wiki/wiki/Design-Rationale"
        ],
        "smart_contracts": [
            "https://en.bitcoin.it/wiki/Script"
        ],
        "masternode": [
            "https://bitcoin.org/bitcoin.pdf"
        ],
        "masternode_deposit": [
            "https://bitcoin.org/bitcoin.pdf"
        ],
        "tx_anonymity": [
            "https://bitcoin.org/en/you-need-to-know",
            "https://bitcoin.org/en/protect-your-privacy",
            "https://en.bitcoin.it/wiki/Anonymity"
        ],
        "treasury": [
            "https://bitcoin.org/bitcoin.pdf"
        ],
        "governance": [
            "https://bitcoin.org/bitcoin.pdf"
        ]
    }
}
