=== software-provider/coindatabase/coindatabase-master/coin_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "pattern": "^[A-Za-z][A-Za-z ]+[A-Za-z]$"
        },
        "symbol": {
            "type": "string",
            "pattern": "^[A-Z]{3,10}$"
        },
        "website_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "blockchain_explorer_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "announcement_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "nodes_explorer_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "message_board_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "twitter_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "reddit_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "wikipedia_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "repo_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "whitepaper_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "telegram_url": {
            "$ref": "#/definitions/list-of-urls"
        },
        "max_supply": {
            "$ref": "#/definitions/extended_number"
        },
        "genesis_block_date": {
            "type": "string"
        },
        "consensus": {
            "oneOf": [
                {"$ref": "#/definitions/consensus_type"},
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/defintions/consensus_type"
                    }
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "blockchain_model": {
            "oneOf": [
                {"$ref": "#/definitions/blockchain_model_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "hash_algo": {
            "type": "string"
        },
        "block_time": {
            "$ref": "#/definitions/extended_number"
        },
        "tx_min_fee": {
            "$ref": "#/definitions/extended_number"
        },
        "block_max_size": {
            "$ref": "#/definitions/data_size"
        },
        "block_reward": {
            "$ref": "#/definitions/extended_number"
        },
        "tx_per_second": {
            "$ref": "#/definitions/extended_number"
        },
        "core_lang": {
            "type": "string"
        },
        "smart_contracts": {
            "oneOf": [
                {"$ref": "#/definitions/smart_contracts_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "tx_anonymity": {
            "oneOf": [
                {"$ref": "#/definitions/tx_anonymity_type"},
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "masternode": {
            "$ref": "#/definitions/extended_boolean"
        },
        "masternode_deposit": {
            "$ref": "#/definitions/extended_number"
        },
        "treasury": {
            "$ref": "#/definitions/extended_boolean"
        },
        "governance": {
            "$ref": "#/definitions/extended_boolean"
        },
        "wikipedia_description": {
            "$ref": "#/definitions/extended_string"
        },
        "references": {
            "type": "object",
            "properties": {
                "name": {"$ref": "#/definitions/list-of-urls"},
                "symbol": {"$ref": "#/definitions/list-of-urls"},
                "website_url": {"$ref": "#/definitions/list-of-urls"},
                "blockchain_explorer_url": {"$ref": "#/definitions/list-of-urls"},
                "announcement_url": {"$ref": "#/definitions/list-of-urls"},
                "nodes_explorer_url": {"$ref": "#/definitions/list-of-urls"},
                "message_board_url": {"$ref": "#/definitions/list-of-urls"},
                "twitter_url": {"$ref": "#/definitions/list-of-urls"},
                "reddit_url": {"$ref": "#/definitions/list-of-urls"},
                "wikipedia_url": {"$ref": "#/definitions/list-of-urls"},
                "repo_url": {"$ref": "#/definitions/list-of-urls"},
                "whitepaper_url": {"$ref": "#/definitions/list-of-urls"},
                "telegram_url": {"$ref": "#/definitions/list-of-urls"},
                "max_supply": {"$ref": "#/definitions/list-of-urls"},
                "genesis_block_date": {"$ref": "#/definitions/list-of-urls"},
                "consensus": {"$ref": "#/definitions/list-of-urls"},
                "hash_algo": {"$ref": "#/definitions/list-of-urls"},
                "block_time": {"$ref": "#/definitions/list-of-urls"},
                "block_max_size": {"$ref": "#/definitions/list-of-urls"},
                "block_reward": {"$ref": "#/definitions/list-of-urls"},
                "tx_per_second": {"$ref": "#/definitions/list-of-urls"},
                "core_lang": {"$ref": "#/definitions/list-of-urls"},
                "smart_contracts": {"$ref": "#/definitions/list-of-urls"},
                "tx_anonymity": {"$ref": "#/definitions/list-of-urls"},
                "tx_min_fee": {"$ref": "#/definitions/list-of-urls"},
                "blockchain_model": {"$ref": "#/definitions/list-of-urls"},
                "masternode": {"$ref": "#/definitions/list-of-urls"},
                "masternode_deposit": {"$ref": "#/definitions/list-of-urls"},
                "treasury": {"$ref": "#/definitions/list-of-urls"},
                "governance": {"$ref": "#/definitions/list-of-urls"},
                "wikipedia_description": {"$ref": "#/definitions/list-of-urls"}
            },
            "additionalProperties": false
        }
    },
    "definitions": {
        "extended_number": {
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "string",
                    "pattern": "^\\d(?:[.\\d]*\\d)?(K|M|B)"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?", "Inf"]
                }
            ]
        },
        "extended_boolean": {
            "oneOf": [
                {
                    "type": "boolean"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "extended_string": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?"]
                }
            ]
        },
        "data_size": {
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "string",
                    "pattern": "^\\d+(KB|MB|GB)"
                },
                {
                    "type": "string",
                    "enum": ["NA", "?", "Inf"]
                }
            ]
        },
        "smart_contracts_type": {
            "type": "string",
            "enum": ["none", "limited", "rich"]
        },
        "tx_anonymity_type": {
            "type": "string",
            "enum": ["never", "optional", "always"]
        },
        "consensus_type": {
            "type": "string",
            "enum": ["proof-of-work", "proof-of-stake", "proof-of-importance"]
        },
        "blockchain_model_type": {
            "type": "string",
            "enum": ["UTXO", "account"]
        },
        "list-of-urls": {
            "type": "array",
            "minItems": 0,
            "maxItems": 3,
            "items": {
                "type": "string",
                "pattern": "^https?://.+"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "symbol",
        "website_url",
        "blockchain_explorer_url",
        "announcement_url",
        "nodes_explorer_url",
        "message_board_url",
        "twitter_url",
        "reddit_url",
        "wikipedia_url",
        "repo_url",
        "whitepaper_url",
        "telegram_url",
        "max_supply",
        "genesis_block_date",
        "consensus",
        "hash_algo",
        "block_time",
        "block_max_size",
        "block_reward",
        "tx_per_second",
        "tx_min_fee",
        "tx_anonymity",
        "core_lang",
        "smart_contracts",
        "blockchain_model",
        "references",
        "masternode",
        "masternode_deposit",
        "treasury",
        "governance",
        "wikipedia_description"
    ]
}

=== software-provider/coindatabase/coindatabase-master/coin/Litecoin.json
{
    "name": "Litecoin",
    "symbol": "LTC",
    "website_url": [
        "https://litecoin.com",
        "https://litecoin.org",
        "https://litecoin.info"
    ],
    "blockchain_explorer_url": [
        "http://explorer.litecoin.net/chain/Litecoin",
        "https://chainz.cryptoid.info/ltc/",
        "https://bitinfocharts.com/ru/litecoin/explorer/"
    ],
    "nodes_explorer_url": [
        "https://bitinfocharts.com/litecoin/nodes/"
    ],
    "message_board_url": [
        "https://litecointalk.io/"
    ],
    "twitter_url": [
        "https://twitter.com/LitecoinProject"
    ],
    "reddit_url": [
        "https://www.reddit.com/r/litecoin/"
    ],
    "telegram_url": [
        "https://t.me/Litecoin"
    ],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/Litecoin"
    ],
    "repo_url": [
        "https://github.com/litecoin-project/litecoin"
    ],
    "whitepaper_url": [
        "https://litecoin.info/Litecoin",
        "https://litecoin.info/User:Iddo/Comparison_between_Litecoin_and_Bitcoin"
    ],
    "announcement_url": [],
    "max_supply": "84M",
    "genesis_block_date": "2011-10-08",
    "consensus": "proof-of-work",
    "hash_algo": "scrypt",
    "block_time": 150,
    "block_max_size": "1MB",
    "block_reward": 25,
    "tx_per_second": "?",
    "tx_min_fee": 0.001,
    "tx_anonymity": "never",
    "core_lang": "C++",
    "smart_contracts": "limited",
    "blockchain_model": "UTXO",
    "masternode": false,
    "masternode_deposit": "NA",
    "treasury": false,
    "governance": false,
    "wikipedia_description": "Litecoin (LTC or ≈Å) is a peer-to-peer cryptocurrency and open source software project released under the MIT/X11 license. Creation and transfer of coins is based on an open source cryptographic protocol and is not managed by any central authority. While inspired by, and in most regards technically nearly identical to Bitcoin (BTC), Litecoin has some technical improvements over Bitcoin, and most other major cryptocurrencies, such as the adoption of Segregated Witness, and the Lightning Network. These effectively allow a greater amount of transactions to be processed by the network in a given time, reducing potential bottlenecks, as seen with Bitcoin. Litecoin also has almost zero payment cost and facilitates payments approximately four times faster than Bitcoin.",
    "references": {
        "max_supply": [
            "https://litecoin.info/Litecoin"
        ],
        "consensus": [
            "https://litecoin.info/Litecoin"
        ],
        "hash_algo": [
            "https://litecoin.info/Litecoin",
            "https://litecoin.info/Scrypt"
        ],
        "block_time": [
            "https://litecoin.info/Litecoin"
        ],
        "block_max_size": [
            "https://www.reddit.com/r/litecoin/comments/523jlw/does_litecoin_have_a_blocksize_limit/"
        ],
        "block_reward": [
            "https://bitinfocharts.com/ru/litecoin/explorer/"
        ],
        "core_lang": [
            "https://github.com/litecoin-project/litecoin"
        ],
        "tx_min_fee": [
            "https://litecoin.info/Transaction_fees"
        ],
        "genesis_block_date": [
            "https://chainz.cryptoid.info/ltc/block.dws?1.htm"
        ],
        "blockchain_model": [
            "https://bitcointalk.org/index.php?topic=1625340.0"
        ],
        "smart_contracts": [
            "https://github.com/litecoin-project/litecoin/pull/279"
        ],
        "masternode": [
            "https://litecoin.info/Litecoin"
        ],
        "masternode_deposit": [
            "https://litecoin.info/Litecoin"
        ],
        "tx_anonymity": [
            "https://bitcoin.org/en/you-need-to-know",
            "https://www.reddit.com/r/litecoin/comments/53c0v6/confidential_transaction_for_litecoin/",
            "https://bitcoin.stackexchange.com/questions/18946/is-it-possible-to-launder-bitcoin-by-exchanging-it-for-litecoin-and-then-back-to"
        ],
        "treasury": [
            "https://litecoin.info/User:Iddo/Comparison_between_Litecoin_and_Bitcoin"
        ],
        "governance": [
            "https://litecoin.info/User:Iddo/Comparison_between_Litecoin_and_Bitcoin"
        ],
        "wikipedia_description": [
            "https://en.wikipedia.org/wiki/Litecoin"
        ]
    }
}

=== software-provider/coindatabase/coindatabase-master/coin/Ethereum.json
{
    "name": "Ethereum",
    "symbol": "ETH",
    "website_url": [
        "https://www.ethereum.org"
    ],
    "blockchain_explorer_url": [
        "https://live.ether.camp",
        "https://etherscan.io"
    ],
    "nodes_explorer_url": [
        "https://www.ethernodes.org/network/1",
        "https://www.ethernodes.org/network/1/nodes"
    ],
    "message_board_url": [
        "https://forum.ethereum.org"
    ],
    "twitter_url": [
        "https://twitter.com/ethereumproject"
    ],
    "reddit_url": [
        "https://www.reddit.com/r/ethereum/"
    ],
    "telegram_url": [],
    "wikipedia_url": [
        "https://en.wikipedia.org/wiki/Ethereum"
    ],
    "repo_url": [
        "https://github.com/ethereum/go-ethereum"
    ],
    "whitepaper_url": [
        "https://github.com/ethereum/wiki/wiki/White-Paper"
    ],
    "announcement_url": [],
    "max_supply": "Inf",
    "genesis_block_date": "2015-07-30",
    "consensus": "proof-of-work",
    "hash_algo": "Ethash",
    "block_time": 15,
    "block_max_size": "Inf",
    "block_reward": 5,
    "tx_per_second": 15,
    "tx_min_fee": "?",
    "tx_anonymity": "never",
    "core_lang": "go",
    "smart_contracts": "rich",
    "blockchain_model": "account",
    "masternode": false,
    "masternode_deposit": "NA",
    "treasury": false,
    "governance": false,
    "wikipedia_description": "Ethereum is an open-source, public, blockchain-based distributed computing platform featuring smart contract (scripting) functionality, which facilitates online contractual agreements. It provides a decentralized Turing-complete virtual machine, the Ethereum Virtual Machine (EVM), which can execute scripts using an international network of public nodes. Ethereum also provides a cryptocurrency  token called \"ether\", which can be transferred between accounts and used to compensate participant nodes for computations performed. \"Gas\", an internal transaction pricing mechanism, is used to mitigate spam and allocate resources on the network. Ethereum was proposed in late 2013 by Vitalik Buterin, a cryptocurrency researcher and programmer. Development was funded by an online crowdsale during Julyâ€“August 2014. The system went live on 30 July 2015, with 11.9 million coins \"premined\" for the crowdsale. This accounts for approximately 13 percent of the total circulating supply. In 2016 Ethereum was forked into two blockchains, as a result of the collapse of The DAO project. The majority fork has retained the name Ethereum (the subject of this article), and the second fork named Ethereum Classic.",
    "references": {
        "blockchain_model": [
            "https://medium.com/@ConsenSys/thoughts-on-utxo-by-vitalik-buterin-2bb782c67e53",
            "https://github.com/ethereum/wiki/wiki/Design-Rationale"
        ],
        "consensus": [
            "https://steemit.com/eth/@daut44/musings-on-ethereum-ethereum-classic"
        ],
        "masternode": [
            "https://forum.ethereum.org/discussion/4393/is-ethereum-heading-towards-a-dash-masternode-type-of-format"
        ],
        "masternode_deposit": [
            "https://forum.ethereum.org/discussion/4393/is-ethereum-heading-towards-a-dash-masternode-type-of-format"
        ],
        "tx_anonymity": [
            "https://www.reddit.com/r/ethereum/comments/3uwo9y/anonymity_in_ethereum/"
        ],
        "treasury": [
            "https://github.com/ethereum/wiki/wiki/White-Paper"
        ],
        "governance": [
            "https://github.com/ethereum/wiki/wiki/White-Paper"
        ],
        "wikipedia_description": [
            "https://en.wikipedia.org/wiki/Ethereum"
        ]
    }
}
